# Introduction to the Numpy Python Library


Numpy is the short form of numerical python. It is a python library that consists of multidimensional array objects and a collections of modules for processing those arrays. Using the numpy library, you can perform the following operations

1. Mathematical and logical operations on arrays
2. Fourier tranforms and modules for shape manipulations
2. Linear algebra and random number generations


## The N-dimensional array object

The most important object in the numpy libarary is the N-dimensional array called the **ndarray**. It describes the collection of the items of the same data types. Unlike normal python lists which can store various data types, an ndarray stores only items of the same data type. To create a numpy array by calling the array function and pass a sequence-like object into it. The array function takes on lists object(s) and returns a numpy array containing the passed data

In [1]:
import numpy as np

np.array([5,6,3,7,9])

array([5, 6, 3, 7, 9])

You can also pass multiple sequence-like objects into the array function. However, the objects should all have the same length. 

In [2]:
data = [[23,45,12,78],[67,89,90,12]]
ndarray = np.array(data)
ndarray

array([[23, 45, 12, 78],
       [67, 89, 90, 12]])

You can see that shape of the ndarray by using **.shape**. The **shape** helps you see the number of rows and columns the ndarray has. In the above example, our data object consists of an ndarray of 2 rows and 4 columns.

In [144]:
ndarray.shape

(2, 4)

You can also see the size of the ndarray by using the **.size**. The **size** is the product of the number of rows and columns.

In [145]:
ndarray.size

8

## Other functions to create ndarrays

### np.zeros

This function helps you to create a numpy array with only zeros. It takes in a number which specifies the number of zeros you want in your numpy array. Alternatively, you can specify number of rows and columns in paranthesis to indicate the shape of the numpy array.

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### np.ones
This function helps you to create a numpy array with only ones. It takes in a number which specifies the number of ones you want in your numpy array. Alternatively, you can specify number of rows and columns in paranthesis to indicate the shape of the numpy array.

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

### np.empty

This function helps you create numpy array of a given shape and type without initializing entries

In [9]:
np.empty([3,3])

array([[2.68156159e+154, 2.68156159e+154, 2.96439388e-323],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [2.68156159e+154, 2.68156159e+154, 1.48219694e-323]])

### np.eye

This function returns a numpy array with ones on the diagonal and zeros elsewhere

In [34]:
np.eye(5,M=4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

### np.arange

This way of creating a numpy array is similar to the python's built-in range(). However, this is faster. It works with ints, floats as well. You can also specify a step parameter.

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
np.arange(1.0, 12)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [13]:
np.arange(4, 60, step=5)

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59])

## Some useful attributes

### np.array.dtype
You can use the **dtype** attribute to check the data type of the numpy object. You may also specify the the data type at the time of creating the numpy array.

In [14]:
arr = np.array([45,65,34,45], dtype=np.int32)
print("Data type name: ",arr.dtype)

Data type name:  int32


### np.array.astype
You can also change the data type of the numpy array by using the **astype** attribute.

In [15]:
arr = arr.astype(np.float64)
print("Changed data type is now: ", arr.dtype)

Changed data type is now:  float64


### Reshaping arrays

Numpy allows you to shape and reshape arrays anytime. Lets take the following examples.

In [16]:
# We are creating a new numpy array using the arange() function
new_array = np.arange(20)
print(new_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [17]:
# Lets set the shape
new_array.shape = (4,5)
new_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [18]:
new_array.shape = (10,2)
new_array

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

### np.array.reshape
You can use the reshape() method to reshape your numpy array. It takes in (rows,column). You can play around with the number of rows and columns but ensure that the product of the rows and columns specified equals the size the numpy array.


In [19]:
new2_array = new_array.reshape(2,10)
new2_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

## Arithmetic operations on Arrays
The usual arithmetic operations (addition, subtraction, multiplication, division, indices etc) in maths apply on numpy arrays too.

In [20]:
array_a = np.arange(1,10, step=2)
array_b = np.arange(11, 20, step = 2)
print("array_a: ",array_a)
print("array_b: ",array_b)
print("Adding: array_a + array_b = ", array_a + array_b)
print("Subtracting: array_a - array_b = ", array_a - array_b)
print("Multiplying: array_a * array_b = ", array_a * array_b)
print("Dividing: array_a / array_b = ", array_a / array_b)
print("Integer Division: array_b // array_a = ", array_b // array_a)
print("Modulo Division: array_a % array_b = ", array_a % array_b)
print("Adding: array_b ** array_a = ", array_b ** array_a)

array_a:  [1 3 5 7 9]
array_b:  [11 13 15 17 19]
Adding: array_a + array_b =  [12 16 20 24 28]
Subtracting: array_a - array_b =  [-10 -10 -10 -10 -10]
Multiplying: array_a * array_b =  [ 11  39  75 119 171]
Dividing: array_a / array_b =  [0.09090909 0.23076923 0.33333333 0.41176471 0.47368421]
Integer Division: array_b // array_a =  [11  4  3  2  2]
Modulo Division: array_a % array_b =  [1 3 5 7 9]
Adding: array_b ** array_a =  [          11         2197       759375    410338673 322687697779]


## Adding and removing element


### np.append & np.insert
Just like the append() in built-in python method, the np.append() adds an element to the end of a numpy array. The insert also helps you to insert an element at a particular index.

In [21]:
my_arr = np.arange(0,50, step=5)
print("The original array: ", my_arr)

The original array:  [ 0  5 10 15 20 25 30 35 40 45]


In [22]:
my_arr = np.append(my_arr,12)
my_arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 12])

In [23]:
my_arr = np.insert(my_arr, 3, 100)
my_arr

array([  0,   5,  10, 100,  15,  20,  25,  30,  35,  40,  45,  12])

### np.delete

**np.delete** allows you to delete elements in numpy arrays. You can delete by index, by row or column


In [24]:
my_arr = np.arange(10)
print("Original Array: ", my_arr)

#Deleting one element by index
del_my_arr = np.delete(my_arr, 0)
print("The result after deleting the first item: ",del_my_arr)

#Deleting multiple elements
delM_my_arr = np.delete(my_arr, [0,1,2])
print("The result after deleting multiple items: ",delM_my_arr)

my_arr.resize(5,2)
print("After resizing: ", my_arr)

#Deleting by row, The first argument is the numpy array you want to manipulate, 
#The second argument is the row index you want to delete
#The third argument specifies that it is a row you want to delete.
delRow_my_arr = np.delete(my_arr, 3, axis=0)
print("The result after deleting a row: ",delRow_my_arr)
delCol_my_arr = np.delete(my_arr, 0, axis=1)
print("The result after deleting a column: ",delCol_my_arr)

Original Array:  [0 1 2 3 4 5 6 7 8 9]
The result after deleting the first item:  [1 2 3 4 5 6 7 8 9]
The result after deleting multiple items:  [3 4 5 6 7 8 9]
After resizing:  [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
The result after deleting a row:  [[0 1]
 [2 3]
 [4 5]
 [8 9]]
The result after deleting a column:  [[1]
 [3]
 [5]
 [7]
 [9]]


## Copying Arrays

Numpy has a function to make copies of arrays

In [146]:
a = b = np.arange(10)
print("Original",a)
a_copy = np.copy(a)
print("Copied", a_copy)

print(a == b) # this does element-wise comparison and returns True
print(a is b) # this does array-wise comparison and returns True
print(a == a_copy) # also element-wise comparisons and returns True
print(a is a_copy) # this does array-wise comparison and return True 
#because one is original and the other is a copy.

Original [0 1 2 3 4 5 6 7 8 9]
Copied [0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True  True  True  True  True  True]
True
[ True  True  True  True  True  True  True  True  True  True]
False


## Broadcasting

Whenever we have a compatible array, we can use broadcasting to do some type of function unto a larger array. Compatible arrays will have the same number of dimensions on either the rows or the columns and 1 on the other side. Let's take an example

In [48]:
a = np.arange(10,90,step=5).reshape(4,4)
print("Original numpy array", a)

Original numpy array [[10 15 20 25]
 [30 35 40 45]
 [50 55 60 65]
 [70 75 80 85]]


In [50]:
# Lets make another array, b with four columns and one row

b = np.arange(4)

array([0, 1, 2, 3])

In [51]:
result = a * b
resul

array([[  0,  15,  40,  75],
       [  0,  35,  80, 135],
       [  0,  55, 120, 195],
       [  0,  75, 160, 255]])

In [52]:
# Let's make another array, c with four rows and one column
c = np.array([[1],[2],[3],[4]])
c

array([[1],
       [2],
       [3],
       [4]])

In [53]:
result2 = a * c
result2

array([[ 10,  15,  20,  25],
       [ 60,  70,  80,  90],
       [150, 165, 180, 195],
       [280, 300, 320, 340]])

## Conditional Expression with Numpy Arrays

In [54]:
a = np.arange(10, 100, step=10)
a > 30

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [55]:
a[a>30]

array([40, 50, 60, 70, 80, 90])

### np.where

It returns the indices of the elements in a numpy array that satisfies a particular condition

In [59]:
m = np.arange(30,150, 10)
m

array([ 30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130, 140])

In [66]:
np.where(m > 50)

(array([ 3,  4,  5,  6,  7,  8,  9, 10, 11]),)

Another way of using the **np.where** is vectorized if-else statements.

In [68]:
list(np.where(m > 70, "Greater Than", "Lesser Than"))

['Lesser Than',
 'Lesser Than',
 'Lesser Than',
 'Lesser Than',
 'Lesser Than',
 'Greater Than',
 'Greater Than',
 'Greater Than',
 'Greater Than',
 'Greater Than',
 'Greater Than',
 'Greater Than']

## Mathematical and Statistical Functions

Numpy has a wide range of mathematical functions/methods that allows you to compute statistics of an entire array or along the rows or columns.

In [74]:
array = np.arange(60, 210, step=10).reshape(5,3)
array

array([[ 60,  70,  80],
       [ 90, 100, 110],
       [120, 130, 140],
       [150, 160, 170],
       [180, 190, 200]])

For each method, we shall compute them over the entire array and along the rows and columns


In [78]:
print("The max of the entire array =",np.max(array))
print("The max along the columns =", array.max(axis=0))
print("The max along the rows =", array.max(axis=1))

The max of the entire array = 200
The max along the columns = [180 190 200]
The max along the rows = [ 80 110 140 170 200]


In [79]:
print("The min of the entire array =",np.min(array))
print("The min along the columns =", array.min(axis=0))
print("The min along the rows =", array.min(axis=1))

The min of the entire array = 60
The min along the columns = [60 70 80]
The min along the rows = [ 60  90 120 150 180]


In [80]:
print("The mean of the entire array =",np.mean(array))
print("The mean along the columns =", array.mean(axis=0))
print("The mean along the rows =", array.mean(axis=1))

The mean of the entire array = 130.0
The mean along the columns = [120. 130. 140.]
The mean along the rows = [ 70. 100. 130. 160. 190.]


In [81]:
print("The product of the entire array =",np.prod(array))
print("The product along the columns =", array.prod(axis=0))
print("The product along the rows =", array.prod(axis=1))

The product of the entire array = 5069473773841809408
The product along the columns = [17496000000 27664000000 41888000000]
The product along the rows = [ 336000  990000 2184000 4080000 6840000]


In [97]:
print("The standard deviation of the entire array =",np.std(array))
print("The standard deviation along the columns =", array.std(axis=0))
print("The standard deviation along the rows =", array.std(axis=1))

The standard deviation of the entire array = 43.20493798938573
The standard deviation along the columns = [42.42640687 42.42640687 42.42640687]
The standard deviation along the rows = [8.16496581 8.16496581 8.16496581 8.16496581 8.16496581]


In [98]:
print("The variance of the entire array =",np.var(array))
print("The variance along the columns =", array.var(axis=0))
print("The variance along the rows =", array.var(axis=1))

The variance of the entire array = 1866.6666666666667
The variance along the columns = [1800. 1800. 1800.]
The variance along the rows = [66.66666667 66.66666667 66.66666667 66.66666667 66.66666667]


In [99]:
print("The sum of the entire array =",np.sum(array))
print("The sum along the columns =", array.sum(axis=0))
print("The sum along the rows =", array.sum(axis=1))

The sum of the entire array = 1950
The sum along the columns = [600 650 700]
The sum along the rows = [210 300 390 480 570]


## Universal Functions

Universal functions are those that make element-wise computations on data in numpy arrays. Their functions takes in a scaler value and returns a scaler numpy array.

In [100]:
new_array = np.arange(30, 120, step=10)
new_array

array([ 30,  40,  50,  60,  70,  80,  90, 100, 110])

### np.square

Calculate the element-wise square of the input

In [101]:
np.square(new_array)

array([  900,  1600,  2500,  3600,  4900,  6400,  8100, 10000, 12100])

### np.exp

Calculate the element-wise exponent of the input

In [102]:
np.exp(new_array)

array([1.06864746e+13, 2.35385267e+17, 5.18470553e+21, 1.14200739e+26,
       2.51543867e+30, 5.54062238e+34, 1.22040329e+39, 2.68811714e+43,
       5.92097203e+47])

## Binary Universal Functions

They take two numpy arrays as arguments and return an array as the result

In [103]:
a = np.array([45,33,78,23])
b = np.array([3,1,6,3])
print(a)
print(b)

[45 33 78 23]
[3 1 6 3]


### np.maximum

It returns the maximum of the element-wise array elements

In [104]:
np.maximum(a,b)

array([45, 33, 78, 23])

### np.minimum

It returns the minimum of the element-wise elements

In [105]:
np.minimum(a,b)

array([3, 1, 6, 3])

### np.power

Elements from the first array raised to the power of the second array element. This is done element-wise

In [106]:
np.power(a,b)

array([       91125,           33, 225199600704,        12167])

## Array Indexing and Slicing

### One dimensional array slicing and indexing

This is similar to normal list indexing and slicing in python. We will jump straight into the multi dimensional array indexing and slicing

### Multi Dimensional Indexing and Slicing

In [108]:
a = np.arange(10,100,step=10).reshape(3,3)
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [110]:
a[2,2] # row three, column three........remember indexing starts from 0

90

In [111]:
a[0,:] # row 1, all column

array([10, 20, 30])

In [112]:
a[:,0] # all rows, column 1

array([10, 40, 70])

## Transposing Arrays

In numpy, we use the **transpose()** method to transpose an array. When you transpose an array, the rows become columns and the columns become rows.

In [113]:
m = np.arange(4, 52, step=4).reshape(3,4)
m


array([[ 4,  8, 12, 16],
       [20, 24, 28, 32],
       [36, 40, 44, 48]])

In [114]:
np.transpose(m)

array([[ 4, 20, 36],
       [ 8, 24, 40],
       [12, 28, 44],
       [16, 32, 48]])

## Combining Arrays

In [115]:
a = np.arange(6)
b = 8 * a
c = 10 + a
print(a)
print(b)
print(c)

[0 1 2 3 4 5]
[ 0  8 16 24 32 40]
[10 11 12 13 14 15]


### np.vstack

Stacks arrays vertically

In [116]:
res = np.vstack((a,b,c))
res

array([[ 0,  1,  2,  3,  4,  5],
       [ 0,  8, 16, 24, 32, 40],
       [10, 11, 12, 13, 14, 15]])

### np.hstack

Stacks arrays horizontally

In [117]:
res1 = np.hstack((a,b,c))
res1

array([ 0,  1,  2,  3,  4,  5,  0,  8, 16, 24, 32, 40, 10, 11, 12, 13, 14,
       15])

## Sorting Arrays

You may use the **sort()** method which sorts in place

In [118]:
res1

array([ 0,  1,  2,  3,  4,  5,  0,  8, 16, 24, 32, 40, 10, 11, 12, 13, 14,
       15])

In [120]:
res1.sort()
res1

array([ 0,  0,  1,  2,  3,  4,  5,  8, 10, 11, 12, 13, 14, 15, 16, 24, 32,
       40])

If you dont want the sorting to happend in place you can use **np.sort()** 

In [122]:
new_array = np.array([45,78,124,46,89,34,18,19,54])
new_array

array([ 45,  78, 124,  46,  89,  34,  18,  19,  54])

In [123]:
sorted_array = np.sort(new_array)
sorted_array

array([ 18,  19,  34,  45,  46,  54,  78,  89, 124])

If you want to reverse the sorted array, you can add **[::-1]** to the end of the **np.sort()**

In [124]:
rev = np.sort(new_array)[::-1]
rev

array([124,  89,  78,  54,  46,  45,  34,  19,  18])

## Saving Arrays

The **np.save()** method allows us to save arrays and load them later.

In [129]:
arr = np.arange(10)
arr2 = np.arange(10, 100, step=10)

In [130]:
# Save single array
np.save('arr',arr)

In [133]:
# Save multiple arrays
np.savez('arrays.npz', x=arr, y=arr2)

In [141]:
# You can also save to txt file
np.savetxt('array.txt', arr,delimiter=',')

## Loading Arrays

Numpy arrays have the extension **npy**. Therefore, you must have the extension when you want to load a numpy array.

In [134]:
# Load single arrays
load_array = np.load('arr.npy')
load_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
# Load multiple arrays
load_multiple = np.load('arrays.npz')

In [137]:
load_multiple['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
load_multiple['y']

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [142]:
# Loading txt file
load_txt = np.loadtxt('array.txt',delimiter=',')

In [143]:
load_txt

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### References

1. https://www.featureranking.com/tutorials/python-tutorials/numpy/